/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote.app;

import java.awt.Toolkit;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author amigo
 */
public class MainApp extends javax.swing.JFrame {
    
    List<String> lista;
    Senha senha = new Senha();
    int n = 1;
    
    public MainApp() {
        initComponents();
        lista = new ArrayList<>();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSenha = new javax.swing.JLabel();
        lblCaixa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnComum = new javax.swing.JButton();
        btnRapido = new javax.swing.JButton();
        btnPrioritario = new javax.swing.JButton();
        txtExibeSenha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCaixa1 = new javax.swing.JButton();
        btnCaixa2 = new javax.swing.JButton();
        btnCaixa4 = new javax.swing.JButton();
        btnCaixa3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Filas");
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setResizable(false);

        lblSenha.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N
        lblSenha.setText("Senha");

        lblCaixa.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N
        lblCaixa.setText("Caixa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        btnComum.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnComum.setText("Comum");
        btnComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComumActionPerformed(evt);
            }
        });

        btnRapido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnRapido.setText("Rápido");
        btnRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRapidoActionPerformed(evt);
            }
        });

        btnPrioritario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnPrioritario.setText("Pioritário");
        btnPrioritario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrioritarioActionPerformed(evt);
            }
        });

        txtExibeSenha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtExibeSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setText("Sua senha é:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel4.setText("Escolha seu tipo de atendimento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnComum)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRapido)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrioritario))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(txtExibeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComum)
                    .addComponent(btnRapido)
                    .addComponent(btnPrioritario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtExibeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para caixas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        btnCaixa1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCaixa1.setText("Caixa 1");
        btnCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa1ActionPerformed(evt);
            }
        });

        btnCaixa2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCaixa2.setText("Caixa 2");
        btnCaixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa2ActionPerformed(evt);
            }
        });

        btnCaixa4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCaixa4.setText("Caixa 4");
        btnCaixa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa4ActionPerformed(evt);
            }
        });

        btnCaixa3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCaixa3.setText("Caixa 3");
        btnCaixa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCaixa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCaixa2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCaixa3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCaixa4)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaixa1)
                    .addComponent(btnCaixa2))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaixa3)
                    .addComponent(btnCaixa4))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCaixa)
                    .addComponent(lblSenha))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lblSenha)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCaixa)
                        .addGap(115, 115, 115))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComumActionPerformed
        senha.setNum(n++);
        senha.setTipo("C-");
        lista.add(senha.getTipo() + senha.getNum());
        txtExibeSenha.setText(senha.getTipo() + senha.getNum());
    }//GEN-LAST:event_btnComumActionPerformed

    private void btnRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRapidoActionPerformed
        senha.setNum(n++);
        senha.setTipo("R-");
        lista.add(senha.getTipo() + senha.getNum());
        txtExibeSenha.setText(senha.getTipo() + senha.getNum());
    }//GEN-LAST:event_btnRapidoActionPerformed

    private void btnPrioritarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrioritarioActionPerformed
        senha.setNum(n++);
        senha.setTipo("P-");
        lista.add(senha.getTipo() + senha.getNum());
        txtExibeSenha.setText(senha.getTipo() + senha.getNum());
    }//GEN-LAST:event_btnPrioritarioActionPerformed

    private void btnCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa1ActionPerformed
        lblCaixa.setText("Caixa 1");
        if(senha.getTipo().toString().contains("P")){
            for (String fila : lista) {
                if(fila.contains("P")){
                    lblSenha.setText(fila);
                    lista.remove(fila);
                    break;
                }
            }
        }else{
            for(String fila : lista){
                lblSenha.setText(fila);
                lista.remove(fila);
                break;
            }
        }
    }//GEN-LAST:event_btnCaixa1ActionPerformed

    private void btnCaixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa2ActionPerformed
        lblCaixa.setText("Caixa 2");
        if(senha.getTipo().toString().contains("R")){
            for (String fila : lista) {
                if(fila.contains("R")){
                    lblSenha.setText(fila);
                    lista.remove(fila);
                    break;
                }
            }
        }else{
            for(String fila : lista){
                lblSenha.setText(fila);
                lista.remove(fila);
                break;
            }
        }
    }//GEN-LAST:event_btnCaixa2ActionPerformed
    
    private void btnCaixa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa4ActionPerformed
        lblCaixa.setText("Caixa 4");
        if(senha.getTipo().toString().contains("C")){
            for (String fila : lista) {
                if(fila.contains("C")){
                    lblSenha.setText(fila);
                    lista.remove(fila);
                    break;
                }
            }
        }else{
            for(String fila : lista){
                lblSenha.setText(fila);
                lista.remove(fila);
                break;
            }
        }
    }//GEN-LAST:event_btnCaixa4ActionPerformed

    private void btnCaixa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa3ActionPerformed
        lblCaixa.setText("Caixa 3");
        if(senha.getTipo().toString().contains("R")){
            for (String fila : lista) {
                if(fila.contains("R"))
                    lblSenha.setText(fila);
                    lista.remove(fila);
                    break;
            }
        }else{
            for(String fila : lista){
                lblSenha.setText(fila);
                lista.remove(fila);
                break;
            }
        }
    }//GEN-LAST:event_btnCaixa3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa1;
    private javax.swing.JButton btnCaixa2;
    private javax.swing.JButton btnCaixa3;
    private javax.swing.JButton btnCaixa4;
    private javax.swing.JButton btnComum;
    private javax.swing.JButton btnPrioritario;
    private javax.swing.JButton btnRapido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCaixa;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtExibeSenha;
    // End of variables declaration//GEN-END:variables
}
